query GetMediaPages($search: String) {
  Page {
    media(search: $search) {
      id
      title {
        english
        native
      }
      description
      bannerImage
    }
  }
}
