query GetMediaPages($search: String, $page: Int) {
  Page(page: $page) {
    pageInfo {
      total
      lastPage
      currentPage
      hasNextPage
      perPage
    }
    media(search: $search) {
      id
      title {
        english
        native
      }
      description
      bannerImage
    }
  }
}
